// Ported from AweMultitool (slfx77)
// (src/AweMultitool/Core/Formats/Granny/Gr2Oodle1Decoder.cs), adapted to this repository's house style.
//
// That file is a C# adaptation of the Granny Oodle1 decompression algorithm from
// carbonenginejs/format-gr2 (https://github.com/carbonenginejs/format-gr2), src/core/oodle1.js, at
// revision c88e9c63016b30cb021e7f204ba7af6f6f58b2d7. CarbonEngineJS marks that file as a
// Boost-licensed port from nwn2mdk; its project-level contributions use this MIT license:
//
//     MIT License
//
//     Copyright (c) 2026 cppctamber / CarbonEngineJS contributors
//
//     Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
//     associated documentation files (the "Software"), to deal in the Software without restriction,
//     including without limitation the rights to use, copy, modify, merge, publish, distribute,
//     sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
//     furnished to do so, subject to the following conditions:
//
//     The above copyright notice and this permission notice shall be included in all copies or
//     substantial portions of the Software.
//
//     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
//     NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
//     NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
//     DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
//     OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
// CarbonEngineJS traces the algorithm to the gr2_decompress implementation in Arbos/nwn2mdk
// (https://github.com/Arbos/nwn2mdk), attributed there to berenm and distributed under the Boost
// Software License 1.0. The referenced file is nwn2mdk-lib/gr2_decompress.cpp; its latest
// source-changing revision is 2e11e0d2a765d0e60f974f31846efdd220fd48ef:
//
//     Boost Software License - Version 1.0 - August 17th, 2003
//
//     Permission is hereby granted, free of charge, to any person or organization obtaining a copy of
//     the software and accompanying documentation covered by this license (the "Software") to use,
//     reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative
//     works of the Software, and to permit third-parties to whom the Software is furnished to do so, all
//     subject to the following:
//
//     The copyright notices in the Software and this entire statement, including the above license
//     grant, this restriction and the following disclaimer, must be included in all copies of the
//     Software, in whole or in part, and all derivative works of the Software, unless such copies or
//     derivative works are solely in the form of machine-executable object code generated by a source
//     language processor.
//
//     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
//     NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
//     NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE
//     LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

using System.Buffers.Binary;

namespace BethesdaMultitool.Core.Formats.Granny;

/// <summary>Decodes Granny's legacy Oodle1 section format.</summary>
/// <remarks>
///     This is the old Granny-specific LZ/arithmetic codec, not the modern RAD Oodle library. See the
///     provenance and licence notices at the top of this file.
///     <para>
///         ⚠ The Van Buren prototype never uses it (0 of 3,282 sections, measured 2026-09-08); it
///         is carried so a later Granny 2 build that does is expanded rather than rejected.
///     </para>
/// </remarks>
internal static class Gr2Oodle1Decoder
{
    private const int ParameterBytes = 36;
    private const int StreamPadding = 8;
    private const int OutputSlack = 512;
    private const int MaximumExpandedSize = 256 * 1024 * 1024;
    private const int MaximumExpansionRatio = 1024;

    private static readonly int[] LongBackReferenceSizes = [128, 192, 256, 512];

    /// <summary>Expands one section whose compression value is <see cref="Gr2Compression.Oodle1" />.</summary>
    public static byte[] Decode(Gr2Section section)
    {
        ArgumentNullException.ThrowIfNull(section);
        if (section.Compression != Gr2Compression.Oodle1)
        {
            throw new ArgumentException($"Section {section.Index} uses {section.Compression}, not Oodle1.",
                nameof(section));
        }

        return Decompress(section.Data.Span, section.ExpandedDataSize, section.First16Bit, section.First8Bit);
    }

    internal static byte[] Decompress(ReadOnlySpan<byte> compressed, int expandedSize, int first16Bit, int first8Bit)
    {
        if (expandedSize < 0 || first16Bit < 0 || first16Bit > first8Bit || first8Bit > expandedSize)
        {
            throw new InvalidDataException("Oodle1 output stops are invalid.");
        }

        if (expandedSize == 0)
        {
            return [];
        }

        if (expandedSize > MaximumExpandedSize || expandedSize > (long)compressed.Length * MaximumExpansionRatio)
        {
            throw new InvalidDataException($"Oodle1 expanded size {expandedSize} exceeds the decoder safety cap.");
        }

        if (compressed.Length <= ParameterBytes)
        {
            throw new InvalidDataException("Oodle1 data is too short for its parameters and stream.");
        }

        Span<Parameters> parameters = stackalloc Parameters[3];
        for (var index = 0; index < parameters.Length; index++)
        {
            parameters[index] = Parameters.Read(compressed.Slice(index * 12, 12));
        }

        var stream = new byte[checked(compressed.Length - ParameterBytes + StreamPadding)];
        compressed[ParameterBytes..].CopyTo(stream);
        var decoder = new ArithmeticDecoder(stream);
        var output = new byte[checked(expandedSize + OutputSlack)];
        Span<int> stops = [first16Bit, first8Bit, expandedSize];

        var cursor = 0;
        for (var segment = 0; segment < stops.Length; segment++)
        {
            var dictionary = new Dictionary(parameters[segment]);
            while (cursor < stops[segment])
            {
                cursor += dictionary.DecompressBlock(decoder, output, cursor);
            }
        }

        return output[..expandedSize];
    }

    private readonly record struct Parameters(
        int DecodedValueMax,
        int BackReferenceValueMax,
        int DecodedCount,
        int HighBitCount,
        byte SizeCount0,
        byte SizeCount1,
        byte SizeCount2,
        byte SizeCount3)
    {
        public byte SizeCount(int index)
        {
            return index switch
            {
                0 => SizeCount0,
                1 => SizeCount1,
                2 => SizeCount2,
                3 => SizeCount3,
                _ => throw new ArgumentOutOfRangeException(nameof(index))
            };
        }

        public static Parameters Read(ReadOnlySpan<byte> data)
        {
            var first = BinaryPrimitives.ReadUInt32LittleEndian(data);
            var second = BinaryPrimitives.ReadUInt32LittleEndian(data[4..]);
            return new Parameters(
                (int)(first & 0x1FF),
                (int)(first >> 9),
                (int)(second & 0x1FF),
                (int)((second >> 19) & 0x1FFF),
                data[8], data[9], data[10], data[11]);
        }
    }

    private sealed class ArithmeticDecoder(byte[] stream)
    {
        private uint _denominator = 0x80;
        private uint _nextDenominator;
        private uint _numerator = (uint)(stream[0] >> 1);
        private int _position;

        public int ReadCumulative(int maximum)
        {
            if (maximum <= 0)
            {
                throw new InvalidDataException("Oodle1 requested an empty arithmetic range.");
            }

            while (_denominator <= 0x800000)
            {
                if (_position + 1 >= stream.Length)
                {
                    throw new InvalidDataException("Oodle1 arithmetic stream is truncated.");
                }

                _denominator = unchecked(_denominator << 8);
                _numerator = unchecked(
                    (_numerator << 8) |
                    (uint)((stream[_position] << 7) & 0x80) |
                    (uint)((stream[_position + 1] >> 1) & 0x7F));
                _position++;
            }

            _nextDenominator = _denominator / (uint)maximum;
            return (int)Math.Min(_numerator / _nextDenominator, (uint)(maximum - 1));
        }

        public int Commit(int maximum, int value, int width)
        {
            _numerator = unchecked(_numerator - _nextDenominator * (uint)value);
            _denominator = value + width < maximum
                ? _nextDenominator * (uint)width
                : unchecked(_denominator - _nextDenominator * (uint)value);
            return value;
        }

        public int DecodeAndCommit(int maximum)
        {
            return Commit(maximum, ReadCumulative(maximum), 1);
        }
    }

    private sealed class WeightedWindow
    {
        private readonly int _countCap;
        private readonly uint _increaseCap;
        private readonly List<ushort> _ranges = [0, 0x4000];
        private readonly List<ushort> _values = [0];
        private readonly uint _weightRebuild;
        private readonly List<ushort> _weights = [4];
        private uint _increase = 4;
        private uint _rangeRebuild = 8;
        private uint _total = 4;

        public WeightedWindow(int maximumValue, int countCap)
        {
            _countCap = countCap + 1;
            _weightRebuild = (uint)Math.Max(256, Math.Min(32 * maximumValue, 15160));
            _increaseCap = maximumValue > 64
                ? (uint)Math.Min(2 * maximumValue, ((int)_weightRebuild >> 1) - 32)
                : 128;
        }

        public ushort StoreValue(int index, int value)
        {
            var stored = checked((ushort)value);
            _values[index] = stored;
            return stored;
        }

        public DecodedSymbol DecodeSymbol(ArithmeticDecoder decoder)
        {
            if (_total >= _rangeRebuild)
            {
                if (_rangeRebuild >= _weightRebuild)
                {
                    RebuildWeights();
                }

                RebuildRanges();
            }

            var value = decoder.ReadCumulative(0x4000);
            var low = 0;
            var high = _ranges.Count;
            while (low < high)
            {
                var middle = (low + high) >> 1;
                if (_ranges[middle] <= value)
                {
                    low = middle + 1;
                }
                else
                {
                    high = middle;
                }
            }

            var rangeIndex = Math.Max(0, low - 1);
            decoder.Commit(0x4000, _ranges[rangeIndex], _ranges[rangeIndex + 1] - _ranges[rangeIndex]);
            _weights[rangeIndex]++;
            _total++;

            if (rangeIndex > 0)
            {
                return new DecodedSymbol(-1, _values[rangeIndex]);
            }

            if (_weights.Count >= _ranges.Count && decoder.DecodeAndCommit(2) == 1)
            {
                var index = _ranges.Count + decoder.DecodeAndCommit(_weights.Count - _ranges.Count + 1) - 1;
                _weights[index] += 2;
                _total += 2;
                return new DecodedSymbol(-1, _values[index]);
            }

            _values.Add(0);
            _weights.Add(2);
            _total += 2;
            if (_weights.Count == _countCap)
            {
                _total -= _weights[0];
                _weights[0] = 0;
            }

            return new DecodedSymbol(_values.Count - 1, 0);
        }

        private void RebuildRanges()
        {
            _ranges.Clear();
            var rangeWeight = 8u * 0x4000u / _total;
            uint rangeStart = 0;
            foreach (var weight in _weights)
            {
                _ranges.Add(checked((ushort)rangeStart));
                rangeStart += weight * rangeWeight / 8;
            }

            _ranges.Add(0x4000);
            if (_increase > _increaseCap >> 1)
            {
                _rangeRebuild = _total + _increaseCap;
            }
            else
            {
                _increase <<= 1;
                _rangeRebuild = _total + _increase;
            }
        }

        private void RebuildWeights()
        {
            uint total = 0;
            for (var index = 0; index < _weights.Count; index++)
            {
                _weights[index] >>= 1;
                total += _weights[index];
            }

            _total = total;
            for (var index = 1; index < _weights.Count; index++)
            {
                while (index < _weights.Count && _weights[index] == 0)
                {
                    var last = _weights.Count - 1;
                    _weights[index] = _weights[last];
                    _values[index] = _values[last];
                    _weights.RemoveAt(last);
                    _values.RemoveAt(last);
                }
            }

            var maximumIndex = -1;
            ushort maximumWeight = 0;
            for (var index = 1; index < _weights.Count; index++)
            {
                if (_weights[index] > maximumWeight)
                {
                    maximumIndex = index;
                    maximumWeight = _weights[index];
                }
            }

            if (maximumIndex >= 0)
            {
                var last = _weights.Count - 1;
                (_weights[maximumIndex], _weights[last]) = (_weights[last], _weights[maximumIndex]);
                (_values[maximumIndex], _values[last]) = (_values[last], _values[maximumIndex]);
            }

            if (_weights.Count < _countCap && _weights[0] == 0)
            {
                _weights[0] = 1;
                _total++;
            }
        }
    }

    private sealed class Dictionary
    {
        private readonly int _backReferenceValueMax;
        private readonly int _decodedValueMax;
        private readonly WeightedWindow[] _decodedWindows;
        private readonly WeightedWindow _highBitWindow;
        private readonly int _lowBitValueMax;
        private readonly WeightedWindow _lowBitWindow;
        private readonly WeightedWindow[] _midBitWindows;
        private readonly WeightedWindow[] _sizeWindows;
        private int _backReferenceSize;
        private int _decodedSize;

        public Dictionary(Parameters parameters)
        {
            _decodedValueMax = parameters.DecodedValueMax;
            _backReferenceValueMax = parameters.BackReferenceValueMax;
            _lowBitValueMax = Math.Min(_backReferenceValueMax + 1, 4);
            var midBitValueMax = Math.Min(_backReferenceValueMax / 4 + 1, 256);
            var highBitValueMax = _backReferenceValueMax / 1024 + 1;

            _lowBitWindow = new WeightedWindow(_lowBitValueMax - 1, _lowBitValueMax);
            _highBitWindow = new WeightedWindow(highBitValueMax - 1, parameters.HighBitCount + 1);
            _midBitWindows = new WeightedWindow[highBitValueMax];
            for (var index = 0; index < _midBitWindows.Length; index++)
            {
                _midBitWindows[index] = new WeightedWindow(midBitValueMax - 1, midBitValueMax);
            }

            _decodedWindows = new WeightedWindow[4];
            for (var index = 0; index < _decodedWindows.Length; index++)
            {
                _decodedWindows[index] = new WeightedWindow(_decodedValueMax - 1, parameters.DecodedCount);
            }

            _sizeWindows = new WeightedWindow[65];
            for (var group = 0; group < 4; group++)
            {
                for (var index = 0; index < 16; index++)
                {
                    _sizeWindows[group * 16 + index] = new WeightedWindow(64, parameters.SizeCount(3 - group));
                }
            }

            _sizeWindows[64] = new WeightedWindow(64, parameters.SizeCount(0));
        }

        public int DecompressBlock(ArithmeticDecoder decoder, byte[] output, int cursor)
        {
            var sizeWindow = _sizeWindows[_backReferenceSize];
            var sizeSymbol = sizeWindow.DecodeSymbol(decoder);
            if (sizeSymbol.NewIndex >= 0)
            {
                sizeSymbol = sizeSymbol with
                {
                    Value = sizeWindow.StoreValue(sizeSymbol.NewIndex, decoder.DecodeAndCommit(_sizeWindows.Length))
                };
            }

            _backReferenceSize = sizeSymbol.Value;
            if (_backReferenceSize == 0)
            {
                var literalWindow = _decodedWindows[cursor & 3];
                var literal = literalWindow.DecodeSymbol(decoder);
                if (literal.NewIndex >= 0)
                {
                    literal = literal with
                    {
                        Value = literalWindow.StoreValue(literal.NewIndex, decoder.DecodeAndCommit(_decodedValueMax))
                    };
                }

                if ((uint)cursor >= (uint)output.Length)
                {
                    throw new InvalidDataException("Oodle1 literal exceeds its output buffer.");
                }

                output[cursor] = (byte)literal.Value;
                _decodedSize++;
                return 1;
            }

            var copyLength = _backReferenceSize < 61
                ? _backReferenceSize + 1
                : LongBackReferenceSizes[_backReferenceSize - 61];
            var backReferenceRange = Math.Min(_backReferenceValueMax, _decodedSize);

            var low = DecodeValue(_lowBitWindow, decoder, _lowBitValueMax);
            var high = DecodeValue(_highBitWindow, decoder, backReferenceRange / 1024 + 1);
            if ((uint)high >= (uint)_midBitWindows.Length)
            {
                throw new InvalidDataException("Oodle1 high back-reference symbol is invalid.");
            }

            var middleWindow = _midBitWindows[high];
            var middle = DecodeValue(middleWindow, decoder, Math.Min(backReferenceRange / 4 + 1, 256));
            var offset = (high << 10) + (middle << 2) + low + 1;
            if (offset > cursor || cursor > output.Length - copyLength)
            {
                throw new InvalidDataException("Oodle1 back-reference is outside its output buffer.");
            }

            _decodedSize += copyLength;
            for (var index = 0; index < copyLength; index++)
            {
                output[cursor + index] = output[cursor - offset + index];
            }

            return copyLength;
        }

        private static int DecodeValue(WeightedWindow window, ArithmeticDecoder decoder, int maximum)
        {
            var symbol = window.DecodeSymbol(decoder);
            return symbol.NewIndex >= 0
                ? window.StoreValue(symbol.NewIndex, decoder.DecodeAndCommit(maximum))
                : symbol.Value;
        }
    }

    private readonly record struct DecodedSymbol(int NewIndex, ushort Value);
}
