namespace EsmAnalyzer.Commands.DialogueVoice;

/// <summary>
///     Stop-word sets used by <see cref="DialogueQcCommand" /> to keep proper-noun
///     case/typo fixes from corrupting ordinary English text.
/// </summary>
internal static class DialogueQcStopWords
{
    // Common English words that would corrupt normal text if "fixed" to a proper-noun
    // capitalization just because the same letters appear in an ESM compound name
    // (e.g. "Great" in "Great Khans" must not turn every "great" into "Great").
    // Used both at vocab-build time (excluded as multi-word FULL tokens) and at
    // fix-application time (skipped on the case-fix and edit-distance paths).
    public static readonly HashSet<string> EnglishStopWords = new(StringComparer.OrdinalIgnoreCase)
    {
        // Articles / pronouns / determiners / conjunctions / prepositions
        "the", "a", "an", "and", "or", "but", "nor", "yet", "so", "if", "then",
        "this", "that", "these", "those", "such", "some", "any", "all", "both", "each", "every", "no", "not",
        "i", "me", "my", "mine", "you", "your", "yours", "he", "him", "his", "she", "her", "hers", "it", "its",
        "we", "us", "our", "ours", "they", "them", "their", "theirs", "who", "whom", "whose", "which", "what",
        "of", "to", "in", "on", "at", "by", "for", "with", "without", "from", "into", "onto", "upon", "over",
        "under", "above", "below", "between", "through", "across", "around", "about", "against", "along",
        "among", "before", "after", "since", "until", "during", "while", "as", "than", "though", "although",
        "because", "unless", "where", "when", "whenever", "wherever", "whether", "until",
        // Auxiliary / common verbs in low frequency forms
        "is", "am", "are", "was", "were", "be", "been", "being",
        "do", "does", "did", "done", "doing",
        "have", "has", "had", "having",
        "can", "could", "shall", "should", "will", "would", "may", "might", "must",
        "go", "goes", "going", "gone", "went",
        "come", "comes", "came", "coming",
        "get", "gets", "got", "getting",
        "say", "says", "said", "saying",
        "see", "sees", "saw", "seen", "seeing",
        "make", "makes", "made", "making",
        "take", "takes", "took", "taken", "taking",
        "give", "gives", "gave", "given", "giving",
        "know", "knows", "knew", "known", "knowing",
        "think", "thinks", "thought", "thinking",
        "look", "looks", "looked", "looking",
        "want", "wants", "wanted", "wanting",
        "use", "uses", "used", "using",
        "find", "finds", "found", "finding",
        "tell", "tells", "told", "telling",
        "ask", "asks", "asked", "asking",
        "work", "works", "worked", "working",
        "try", "tries", "tried", "trying",
        "leave", "leaves", "left", "leaving",
        "call", "calls", "called", "calling",
        "feel", "feels", "felt", "feeling",
        "keep", "keeps", "kept", "keeping",
        "let", "lets", "letting",
        "begin", "begins", "began", "begun",
        "show", "shows", "showed", "shown",
        "bring", "brings", "brought",
        "follow", "follows", "followed",
        "stand", "stands", "stood",
        "lose", "loses", "lost", "losing",
        "pay", "pays", "paid",
        "live", "lives", "lived", "living",
        "meet", "meets", "met",
        "run", "runs", "ran", "running",
        "move", "moves", "moved", "moving",
        "like", "likes", "liked",
        "believe", "believes", "believed",
        "hold", "holds", "held", "holding",
        "turn", "turns", "turned",
        "set", "sets", "setting",
        "start", "starts", "started", "starting",
        "lead", "leads", "led",
        "hear", "hears", "heard",
        "stop", "stops", "stopped",
        "play", "plays", "played",
        "speak", "speaks", "spoke", "spoken",
        "read", "reads", "reading",
        "spend", "spent",
        "grow", "grows", "grew", "grown",
        "win", "wins", "won",
        "buy", "buys", "bought",
        "wait", "waits", "waited",
        "serve", "served",
        "die", "dies", "died",
        "send", "sent",
        "build", "builds", "built",
        "stay", "stays", "stayed",
        "fall", "falls", "fell", "fallen",
        "cut", "cuts", "cutting",
        "reach", "reached",
        "kill", "kills", "killed",
        "remain", "remained",
        "carry", "carries", "carried",
        "raise", "raised",
        "drink", "drinks", "drank",
        "open", "opens", "opened",
        "walk", "walks", "walked",
        "wear", "wears", "wore", "worn",
        "fight", "fights", "fought",
        "sit", "sits", "sat",
        "lay", "lays", "laid",
        "watch", "watches", "watched",
        "rest", "rests", "rested",
        "wonder", "wondered",
        "hope", "hopes", "hoped",
        "pull", "pulls", "pulled",
        "draw", "draws", "drew", "drawn",
        "throw", "throws", "threw", "thrown",
        // Common adjectives / adverbs / quantifiers / time / place
        "good", "great", "bad", "old", "new", "young", "long", "short", "high", "low",
        "big", "small", "large", "little", "tall", "wide", "deep",
        "more", "less", "many", "much", "few", "most", "least", "enough", "lot", "lots",
        "first", "second", "third", "last", "next", "only",
        "best", "better", "worst", "worse",
        "early", "late", "later", "soon", "sooner", "now", "never", "always", "often",
        "again", "still", "ever", "ago", "today", "yesterday", "tomorrow",
        "here", "there", "everywhere", "anywhere", "nowhere",
        "out", "in", "inside", "outside", "back", "front", "side",
        "up", "down", "off", "on", "away", "near", "far",
        "left", "right", "north", "south", "east", "west",
        "home", "house", "room", "town", "city", "world",
        "way", "ways", "place", "places", "time", "times",
        "day", "days", "night", "nights", "year", "years", "week", "weeks", "month", "months", "hour", "hours",
        "thing", "things", "stuff",
        "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
        "zero", "hundred", "thousand", "million",
        "really", "very", "just", "even", "also", "too", "perhaps", "maybe", "actually",
        "yes", "no", "okay", "ok",
        "name", "names",
        "people", "person", "man", "men", "woman", "women", "boy", "girl", "kid", "child",
        "head", "hand", "foot", "eye", "face", "arm", "leg", "body",
        "life", "death", "war", "peace",
        "water", "fire", "earth", "air",
        "kind", "kinds", "type", "types", "sort", "sorts",
        "case", "cases", "fact", "facts", "story",
        "money", "food", "work", "job", "company", "business",
        "fine", "okay", "true", "false", "real", "fake",
        "alone", "together", "ourselves", "yourselves", "themselves", "myself", "yourself", "himself", "herself",
        "itself",
        // Common nouns / generic NPC titles that exist as single-word FULL strings in FNV
        // and would otherwise drive false-positive case-fixes on every dialogue use.
        "guard", "guards", "soldier", "soldiers", "trooper", "troopers", "ranger", "rangers",
        "citizen", "citizens", "settler", "settlers", "doctor", "doctors", "nurse", "nurses",
        "captain", "lieutenant", "colonel", "major", "sergeant", "general", "chief",
        "boss", "bosses", "chairman", "chairmen", "president", "secretary",
        "slave", "slaves", "stranger", "strangers", "traveler", "travelers",
        "junkie", "junkies", "drunk", "drunks", "escort", "escorts",
        "raider", "raiders", "robot", "robots", "ant", "ants", "rat", "rats",
        "dog", "dogs", "cat", "cats", "fiend", "fiends", "mutant", "mutants",
        "ghoul", "ghouls", "deathclaw", "deathclaws",
        "vault", "vaults", "lucky", "fantastic", "meat", "sweetie", "baby", "babies",
        "trash", "loyal", "gift", "gifts", "members", "member", "friend", "friends",
        "family", "families", "mountain", "mountains", "area", "supply", "security",
        "medical", "control", "hell", "power", "powder", "easy", "song", "songs",
        "mess", "miss", "missing", "service", "services", "news",
        "caravan", "caravans", "gang", "gangs", "pack", "packs", "base", "bases",
        "road", "roads", "river", "rivers", "valley", "valleys", "canyon", "canyons",
        "building", "buildings", "station", "stations", "motor", "society", "societies",
        "battle", "battles", "war", "wars", "fight", "fights", "crash", "crashed",
        "saint", "saints", "human", "humans", "creature", "creatures",
        "king", "queen", "lord", "lady", "sir", "madam",
        "north", "south", "east", "west", "central", "downtown", "uptown",
        "sun", "sunset", "sunrise", "moon", "star", "stars",
        "happy", "sad", "angry", "scared", "tired", "hungry", "thirsty",
        "blue", "red", "green", "yellow", "black", "white", "brown", "gray", "grey",
        "shop", "shopper", "shopping", "store", "stores", "market", "markets",
        // Generic occupational nouns that show up as both vocab proper-nouns and common dialogue terms.
        "local", "locals", "hunter", "hunters", "merchant", "merchants", "patient", "patients",
        "gambler", "gamblers", "prospector", "prospectors", "mercenary", "mercenaries",
        "roller", "rollers", "assistant", "assistants", "hooker", "hookers", "bartender", "bartenders",
        "thug", "thugs", "angel", "angels", "drill", "heavy", "field", "fields", "jackass",
        "bouncer", "bouncers", "dealer", "dealers", "patron", "patrons", "owner", "owners",
        "smith", "smiths", "cook", "cooks", "chef", "chefs", "engineer", "engineers",
        "scientist", "scientists", "scholar", "scholars", "teacher", "teachers",
        "leader", "leaders", "follower", "followers", "manager", "managers"
    };

    // Articles/conjunctions/prepositions that should never seed vocab tokens, even when
    // they appear capitalized in a multi-word FULL string ("The Strip", "Of The Patriots").
    public static readonly HashSet<string> StructuralWords = new(StringComparer.OrdinalIgnoreCase)
    {
        "the", "a", "an", "and", "or", "but", "nor", "yet", "so", "if",
        "of", "to", "in", "on", "at", "by", "for", "with", "from", "into", "onto",
        "as", "than", "is", "are", "was", "were", "be"
    };
}