// Ported from daggerfall-unity's DaggerfallConnect API (MIT License),
//   https://github.com/Interkarma/daggerfall-unity — Assets/Scripts/API/Arch3dFile.cs
//   (DecomposeMesh, WritePlane, WriteVariablePlane, GetCornerPoints) and
//   Assets/Scripts/API/Utility/FaceUVTool.cs (ComputeFaceUVCoordinates, l_ComputeDFUVMatrixXY).
//   License texts are collected centrally in THIRD_PARTY_LICENSES.

using System.Numerics;

namespace BethesdaMultitool.Core.Formats.Xngine.Mesh;

/// <summary>A vertex ready for rendering: world-unit position, normal and texel-unit UV.</summary>
internal readonly record struct XnGineVertex(Vector3 Position, Vector3 Normal, Vector2 TexelUv);

/// <summary>Triangles sharing one texture.</summary>
internal sealed class XnGineSubMesh
{
    public XnGineSubMesh(int textureArchive, int textureRecord, IReadOnlyList<XnGineVertex> vertices, IReadOnlyList<int> indices)
    {
        TextureArchive = textureArchive;
        TextureRecord = textureRecord;
        Vertices = vertices;
        Indices = indices;
    }

    public int TextureArchive { get; }

    public int TextureRecord { get; }

    public IReadOnlyList<XnGineVertex> Vertices { get; }

    /// <summary>Triangle list, three indices per triangle.</summary>
    public IReadOnlyList<int> Indices { get; }

    public int TriangleCount => Indices.Count / 3;
}

/// <summary>A decomposed mesh: one submesh per texture, in the mesh's native Y-down space.</summary>
internal sealed class XnGineTriangleMesh
{
    public XnGineTriangleMesh(uint objectId, float radius, Vector3 size, IReadOnlyList<XnGineSubMesh> subMeshes)
    {
        ObjectId = objectId;
        Radius = radius;
        Size = size;
        SubMeshes = subMeshes;
    }

    public uint ObjectId { get; }

    /// <summary>Bounding radius in world units.</summary>
    public float Radius { get; }

    /// <summary>Extent in world units.</summary>
    public Vector3 Size { get; }

    public IReadOnlyList<XnGineSubMesh> SubMeshes { get; }

    public int TriangleCount => SubMeshes.Sum(s => s.TriangleCount);

    public int VertexCount => SubMeshes.Sum(s => s.Vertices.Count);
}

/// <summary>
///     Turns a parsed <see cref="XnGineMesh" /> into textured triangle lists the way the reference
///     does: planes are grouped by texture; a triangle's three UVs are accumulated deltas; a
///     larger polygon has its collinear points dropped (corner detection) and its UVs beyond the
///     third point generated by fitting a linear U/V map to the first three, then it is fanned
///     from its first corner.
/// </summary>
internal static class XnGineMeshDecomposer
{
    /// <summary>Angle (radians) below which three consecutive points count as collinear.</summary>
    private const double CornerAngleThreshold = 0.001;

    public static XnGineTriangleMesh Decompose(XnGineMesh mesh)
    {
        ArgumentNullException.ThrowIfNull(mesh);

        var builders = new List<SubMeshBuilder>();
        foreach (var plane in mesh.Planes)
        {
            if (plane.Points.Count < 3)
            {
                continue;
            }

            var points = new PurePoint[plane.Points.Count];
            for (var i = 0; i < points.Length; i++)
            {
                var source = plane.Points[i];
                var position = mesh.Points[source.PointIndex];
                points[i] = new PurePoint(position, plane.Normal, source.U, source.V);
            }

            var polygon = points.Length == 3 ? Triangle(points) : Polygon(points);
            if (polygon.Length < 3)
            {
                continue;
            }

            var builder = builders.Find(b => b.Archive == plane.TextureArchive && b.Record == plane.TextureRecord);
            if (builder is null)
            {
                builder = new SubMeshBuilder(plane.TextureArchive, plane.TextureRecord);
                builders.Add(builder);
            }

            builder.AddPolygon(polygon);
        }

        var size = mesh.Size;
        return new XnGineTriangleMesh(
            mesh.ObjectId,
            mesh.RadiusUnits,
            new Vector3(size.X, size.Y, size.Z),
            builders.Select(b => b.Build()).ToList());
    }

    /// <summary>A three-point plane: the second and third UVs are deltas from their predecessor.</summary>
    private static PurePoint[] Triangle(PurePoint[] points)
    {
        points[1] = points[1] with { U = points[1].U + points[0].U, V = points[1].V + points[0].V };
        points[2] = points[2] with { U = points[2].U + points[1].U, V = points[2].V + points[1].V };
        return points;
    }

    /// <summary>A larger plane: generated UVs where the fit succeeds, then corner points only.</summary>
    private static PurePoint[] Polygon(PurePoint[] points)
    {
        var corners = CornerIndices(points);
        var generated = ComputeFaceUv(points);
        var source = generated ?? points;
        var result = new PurePoint[corners.Count];
        for (var i = 0; i < corners.Count; i++)
        {
            result[i] = source[corners[i]];
        }

        return result;
    }

    /// <summary>
    ///     The reference's corner test: for each point, the angle at the NEXT point between the
    ///     edges to it and to the one after; a straight run (angle below the threshold) is dropped.
    /// </summary>
    internal static List<int> CornerIndices(PurePoint[] points)
    {
        var corners = new List<int>(points.Length);
        var count = points.Length;
        for (var i = 0; i < count; i++)
        {
            Vector3 v0 = points[i].Position, v1, v2;
            int cornerIndex;
            if (i < count - 2)
            {
                v1 = points[i + 1].Position;
                v2 = points[i + 2].Position;
                cornerIndex = i + 1;
            }
            else if (i < count - 1)
            {
                v1 = points[i + 1].Position;
                v2 = points[0].Position;
                cornerIndex = i + 1;
            }
            else
            {
                v1 = points[0].Position;
                v2 = points[1].Position;
                cornerIndex = 0;
            }

            var l0 = v1 - v0;
            var l1 = v2 - v0;
            var lengths = l0.Length() * l1.Length();
            var angle = lengths > 0 ? Math.Acos(Math.Clamp(Vector3.Dot(l0, l1) / lengths, -1f, 1f)) : double.NaN;
            if (angle > CornerAngleThreshold)
            {
                corners.Add(cornerIndex);
            }
        }

        return corners;
    }

    /// <summary>
    ///     The reference's <c>ComputeFaceUVCoordinates</c>: project the polygon onto its own plane,
    ///     fit <c>U = A·x + B·y + D</c> (and V) through the first three points' accumulated UVs and
    ///     evaluate it for every later point. Null when the three points are collinear.
    /// </summary>
    internal static PurePoint[]? ComputeFaceUv(PurePoint[] points)
    {
        var p0 = points[0].Position;
        var p1 = points[1].Position;
        var p2 = points[2].Position;

        var axisU = p1 - p0;
        var axisV = p2 - p0;
        // A dot product of a vector with itself is never negative, so "not positive" is exactly
        // "zero-length edge" without comparing a float for equality.
        var axisUDot = Vector3.Dot(axisU, axisU);
        if (axisUDot <= 0)
        {
            return null;
        }

        axisV -= axisU * (Vector3.Dot(axisV, axisU) / axisUDot);
        axisU = Vector3.Normalize(axisU);
        axisV = Vector3.Normalize(axisV);

        var x0 = (int)Vector3.Dot(p0, axisU);
        var y0 = (int)Vector3.Dot(p0, axisV);
        var x1 = (int)Vector3.Dot(p1, axisU);
        var y1 = (int)Vector3.Dot(p1, axisV);
        var x2 = (int)Vector3.Dot(p2, axisU);
        var y2 = (int)Vector3.Dot(p2, axisV);

        float u0 = points[0].U, v0 = points[0].V;
        float u1 = points[1].U + u0, v1 = points[1].V + v0;
        float u2 = points[2].U + u1, v2 = points[2].V + v1;

        // The reference rejects an exactly singular matrix; the range spells that without a float
        // equality test (float.Epsilon is the smallest denormal, so this admits nothing else).
        var determinant = x0 * (float)y1 + y0 * (float)x2 + x1 * (float)y2 - y1 * (float)x2 - y0 * (float)x1 - x0 * (float)y2;
        if (determinant is > -float.Epsilon and < float.Epsilon)
        {
            return null;
        }

        var xi0 = (y1 - y2) / determinant;
        var xi1 = (-x1 + x2) / determinant;
        var xi2 = (x1 * (float)y2 - x2 * (float)y1) / determinant;
        var yi0 = (-y0 + y2) / determinant;
        var yi1 = (x0 - x2) / determinant;
        var yi2 = (-x0 * (float)y2 + x2 * (float)y0) / determinant;
        var zi0 = (y0 - y1) / determinant;
        var zi1 = (-x0 + x1) / determinant;
        var zi2 = (x0 * (float)y1 - x1 * (float)y0) / determinant;

        var ua = u0 * xi0 + u1 * yi0 + u2 * zi0;
        var ub = u0 * xi1 + u1 * yi1 + u2 * zi1;
        var ud = u0 * xi2 + u1 * yi2 + u2 * zi2;
        var va = v0 * xi0 + v1 * yi0 + v2 * zi0;
        var vb = v0 * xi1 + v1 * yi1 + v2 * zi1;
        var vd = v0 * xi2 + v1 * yi2 + v2 * zi2;

        var result = new PurePoint[points.Length];
        for (var i = 0; i < points.Length; i++)
        {
            int u, v;
            switch (i)
            {
                case 0:
                    u = (int)u0;
                    v = (int)v0;
                    break;
                case 1:
                    u = (int)u1;
                    v = (int)v1;
                    break;
                case 2:
                    u = (int)u2;
                    v = (int)v2;
                    break;
                default:
                    var x = (int)Vector3.Dot(points[i].Position, axisU);
                    var y = (int)Vector3.Dot(points[i].Position, axisV);
                    u = (int)(x * ua + y * ub + ud);
                    v = (int)(x * va + y * vb + vd);
                    break;
            }

            result[i] = points[i] with { U = u, V = v };
        }

        return result;
    }

    /// <summary>A plane point with its position, the plane normal and raw UVs, in native units.</summary>
    internal readonly record struct PurePoint(Vector3 Position, Vector3 Normal, int U, int V)
    {
        public PurePoint(XnGineMeshPoint position, XnGineMeshPoint normal, int u, int v)
            : this(new Vector3(position.X, position.Y, position.Z), new Vector3(normal.X, normal.Y, normal.Z), u, v)
        {
        }
    }

    private sealed class SubMeshBuilder
    {
        private readonly List<XnGineVertex> _vertices = [];
        private readonly List<int> _indices = [];

        public SubMeshBuilder(int archive, int record)
        {
            Archive = archive;
            Record = record;
        }

        public int Archive { get; }

        public int Record { get; }

        public void AddPolygon(PurePoint[] polygon)
        {
            var first = _vertices.Count;
            foreach (var point in polygon)
            {
                var normal = point.Normal / XnGineMesh.PointDivisor;
                if (normal.LengthSquared() > 0)
                {
                    normal = Vector3.Normalize(normal);
                }

                _vertices.Add(new XnGineVertex(
                    point.Position / XnGineMesh.PointDivisor,
                    normal,
                    new Vector2(point.U / XnGineMesh.TextureDivisor, point.V / XnGineMesh.TextureDivisor)));
            }

            for (var i = 1; i + 1 < polygon.Length; i++)
            {
                _indices.Add(first);
                _indices.Add(first + i);
                _indices.Add(first + i + 1);
            }
        }

        public XnGineSubMesh Build()
        {
            return new XnGineSubMesh(Archive, Record, _vertices, _indices);
        }
    }
}
