using EsmSchemaGen.Emit;
using EsmSchemaGen.Ir;
using Xunit;

namespace EsmSchemaGen.Tests;

public class SchemaEmitterTests
{
    [Fact]
    public void Emits_Record_With_Struct_Enum_And_Unused()
    {
        var rec = new IrBuilder().BuildRecord("""
            wbRecord(TES3, 'Main File Header', [
              wbStruct(HEDR, 'Header', [
                wbInteger('Version', itU32, wbEnum(['A','B'])),
                wbUnused(3)
              ]).SetRequired
            ])
            """);

        var cs = SchemaEmitter.EmitGame("Tes3Schema", [rec]);

        Assert.Contains("// <auto-generated/>", cs, StringComparison.Ordinal);
        Assert.Contains("namespace BethesdaMultitool.Core.Formats.Esm.RecordModel.Generated;", cs, StringComparison.Ordinal);
        Assert.Contains("public static class Tes3Schema", cs, StringComparison.Ordinal);
        Assert.Contains("public static IReadOnlyList<RecordDef> Records { get; } =", cs, StringComparison.Ordinal);
        Assert.Contains("new RecordDef(\"TES3\",", cs, StringComparison.Ordinal);
        Assert.Contains("new StructDef(", cs, StringComparison.Ordinal);
        Assert.Contains("Signature = \"HEDR\"", cs, StringComparison.Ordinal);
        Assert.Contains("Required = true", cs, StringComparison.Ordinal);
        Assert.Contains("new FieldDef(PrimType.U32)", cs, StringComparison.Ordinal);
        Assert.Contains("InlineEnum = new EnumDef(null, [new EnumMember(0, \"A\"), new EnumMember(1, \"B\")])",
            cs, StringComparison.Ordinal);
        Assert.Contains("new UnusedDef(3)", cs, StringComparison.Ordinal);
    }

    [Fact]
    public void Emits_FormId_Targets_And_Raw_Member()
    {
        var rec = new IrBuilder().BuildRecord(
            "wbRecord(WEAP, 'Weapon', [ wbFormIDCk(SCRI, 'Script', [SCPT]), wbNotModeledYet ])");

        var cs = SchemaEmitter.EmitGame("X", [rec]);

        Assert.Contains("new FormIdDef { Signature = \"SCRI\", Name = \"Script\", Targets = [\"SCPT\"] }",
            cs, StringComparison.Ordinal);
        Assert.Contains("new RawMemberDef(\"wbNotModeledYet\")", cs, StringComparison.Ordinal);
    }
}
