using Xunit;

namespace BethesdaMultitool.Tests.Core.Modeling.RealAsset;

/// <summary>
///     The checked-in cut-1c cover manifest against its contract, without any real asset: the parser's rules (each with
///     a synthetic manifest that breaks exactly one), and the manifest facts the plan measured (plan
///     <c>docs/design/cut1c-xngine-reader-plan-20260925.md</c>, section 9 "Cover"), each digest pinned here
///     independently of the manifest file so a regenerated manifest that drops a row, moves a pin to another copy, or
///     swaps the BARSTEP1 namesake pair fails without any game install present.
/// </summary>
/// <remarks>
///     The folded-fan row is pinned to M-Z's pick (3D.BSA CAT02.3D #1111), so a regeneration that reverts to
///     another pick fails here without any game install present.
///     The independent pins were re-measured from the retail containers on 2026-09-28 by
///     <c>TestOutput/cut1c-20260928/slice12/slice1/cut1c_cover_manifest.py</c> (fresh slicing code; 28 of 28 rows
///     reproduced the digests the plan quotes, LZSS payload and stored digests separately). The BARSTEP1 pair is the
///     slice-1 control's heart: the 3D.BSA namesake (#438) has the SAME payload size as the 3D.BS6 cover entry
///     (#437), 1,540 bytes, so only the digests separate them; a size-only comparison cannot.
///     The slice-5 review (2026-09-28) added three edge rows, regenerated by
///     <c>TestOutput/cut1c-20260928/slice56/cut1c_cover_manifest.py</c> (31 of 31 rows reproduced): ARCH3D 409, where
///     the D2 unfold changes stored values; 3D.BSA PUZSPRT1.3D, a face that repeats a source point; and NECRISLE.ROB
///     NCGATE01, both a repeated-point face and the Redguard values only the legacy route unfolds.
/// </remarks>
public sealed class Cut1cCoverManifestTests
{
    private const string LooseSha = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    private const string ArchiveSha = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    private const string StoredSha = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";

    /// <summary>The 3D.BS6 BARSTEP1 cover pins (payload and stored), as the plan quotes them.</summary>
    private const string Barstep1Bs6Sha = "e714112cfb4752f19ae7912e29eb2bba503e117c0e6bebe98e5cc44d30de90c2";

    private const string Barstep1Bs6StoredSha = "5f1ecaed2e34eff2c96cd765246ef7a90920074fd3e88d234afafc949c13e436";

    /// <summary>The 3D.BSA namesake pins (#438; measured, different bytes at the same payload size).</summary>
    private const string Barstep1NamesakeSha = "1ad5586cd66e481da590c98ccde1f74dc04a55bbb1fe35e1eb58a74093abb250";

    private const string Barstep1NamesakeStoredSha =
        "ad4cef083741e3a66a14a3eab70a860b99e7ee44f7aacfc70bf709accf524251";

    /// <summary>SHA-256 of zero bytes (the empty ROB segment's payload pin).</summary>
    private const string EmptySha = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

    /// <summary>
    ///     The M-Z folded-fan pick's pins (3D.BSA CAT02.3D #1111, payload and stored; slice-2 receipt
    ///     m_z_zero_normals_folded.json, restated by slice 1's cut1c_folded_fan_pick.py).
    /// </summary>
    private const string Cat02Sha = "e243414b3ae256de9e52afb7b1323052328a910c92f52f9882449ef00feebcf5";

    private const string Cat02StoredSha = "408bb35c7a93477cf1b85c29936170f292323898c9bbe92456dc0defd8d671c2";

    /// <summary>
    ///     The slice-5 review's ARCH3D 409 payload pin (index 4762), measured by <c>slice56/measure_review_fixes.py</c>
    ///     through the gate-1c oracle's slicers, as are the three pins below.
    /// </summary>
    private const string Arch3d409Sha = "fdf7351c94e95d801aafe9863eca352297f6a2dafbd08699418a04b572f7649f";

    /// <summary>The 3D.BSA PUZSPRT1.3D (#98) decoded payload pin.</summary>
    private const string Puzsprt1Sha = "6376861f503a3bfb9e28ceeaeee33349f21015d881514d9b4861839f50e25e60";

    /// <summary>The 3D.BSA PUZSPRT1.3D (#98) stored (LZSS) pin.</summary>
    private const string Puzsprt1StoredSha = "48d72227b36a99c6dd77590b7fba6f4a7f9e89087f31057102c35b37b4a160c5";

    /// <summary>The NECRISLE.ROB NCGATE01 (segment 108) payload pin.</summary>
    private const string Ncgate01Sha = "bd2b88602418b2ec6a0cb551f42ff4e2001005b4b06de771c4e998173847a14a";

    private const string ManifestJson = """
        {
         "tool": "cut1c_cover_manifest.py",
         "manifestSchema": 1,
         "options": {"scope": "SCOPE", "payloads": true},
         "files": [
          {"role": "ROLE", "name": "NAME1", "game": "Redguard", "population": "redguard_3dc_3dart",
           "container": "loose", "source": "Sample/a/B.3DC", "entry": "B.3DC", "index": LOOSEINDEX, "tag": "v2.7",
           "size": LOOSESIZE, "sha256": "LOOSESHA", "alsoIn": [], "controls": [CONTROLS1]DECLINED1SEGTYPE1, "note": "n"},
          {"role": "proposed", "name": "NAME2", "game": "Battlespire", "population": "battlespire_3d_bs6",
           "container": "xngine-bsa", "source": "Sample/a/3D.BS6", "entry": "C.3D", "index": ARCHIVEINDEX,
           "tag": "v2.7", "size": 20, "sha256": "ARCHIVESHA", "storedSize": STOREDSIZE,
           "storedSha256": STOREDSHA, "alsoIn": [ALSOIN], "controls": [CONTROLS2], "note": "n"}
         ]
        }
        """;

    [Fact]
    public void Parse_ReadsRolesControlsAndStoredPins()
    {
        var files = Cut1cCoverManifest.Parse(Manifest());
        Assert.Equal(2, files.Count);
        var loose = files[0];
        Assert.Equal(Cut1cCoverFile.LooseContainer, loose.Container);
        Assert.Null(loose.Index);
        Assert.False(loose.IsCompressed);
        Assert.Equal("the control", Assert.Single(loose.Controls));
        var archive = files[1];
        Assert.True(archive.IsCompressed);
        Assert.Equal(9L, archive.StoredSize);
        Assert.Equal(StoredSha, archive.StoredSha256);
        Assert.Equal(3, archive.Index);
        Assert.Single(archive.Candidates);
    }

    [Theory]
    [InlineData("cut1a")]
    [InlineData("")]
    public void Parse_RefusesAManifestOfAnotherScope(string scope)
    {
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(scope: scope)));
        Assert.Contains("scope cut1c", exception.Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("cover")]
    [InlineData("Design")]
    [InlineData("")]
    public void Parse_RefusesAnUnknownRole(string role)
    {
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(role: role)));
        Assert.Contains("is not one of", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAMalformedDigest()
    {
        var json = Manifest().Replace(LooseSha, LooseSha.ToUpperInvariant(), StringComparison.Ordinal);
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(json));
        Assert.Contains("malformed SHA-256", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAnEmptyPayloadOutsideADeclineControl()
    {
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(looseSize: 0)));
        Assert.Contains("empty payload is legal only on a decline control", exception.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_AcceptsAnEmptyPayloadOnADeclineControl()
    {
        var files = Cut1cCoverManifest.Parse(Manifest(role: Cut1cCoverFile.DeclinedControlRole, looseSize: 0,
            declined: "empty ROB segment (size 0): no bytes to read"));
        Assert.Equal(0, files[0].Size);
        Assert.True(files[0].IsDeclinedControl);
    }

    [Fact]
    public void Parse_RefusesADeclineControlWithoutAReason()
    {
        var exception = Assert.Throws<InvalidDataException>(() =>
            Cut1cCoverManifest.Parse(Manifest(role: Cut1cCoverFile.DeclinedControlRole)));
        Assert.Contains("decline reason appears exactly on a decline control", exception.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesADeclineReasonOnANonControlRow()
    {
        var exception = Assert.Throws<InvalidDataException>(() =>
            Cut1cCoverManifest.Parse(Manifest(declined: "some reason")));
        Assert.Contains("decline reason appears exactly on a decline control", exception.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAnIndexOnALooseRow()
    {
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(looseIndex: "7")));
        Assert.Contains("carries an index exactly when it is inside an archive", exception.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAnArchiveRowWithoutAnIndex()
    {
        var exception = Assert.Throws<InvalidDataException>(() =>
            Cut1cCoverManifest.Parse(Manifest(archiveIndex: "null")));
        Assert.Contains("carries an index exactly when it is inside an archive", exception.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAStoredSizeWithoutItsDigest()
    {
        var json = Manifest().Replace("\"storedSha256\": \"" + StoredSha + "\"", "\"storedSha256\": null",
            StringComparison.Ordinal);
        Assert.NotEqual(Manifest(), json);
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(json));
        Assert.Contains("only as a pair", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesStoredPinsOnAContainerThatNeverCompresses()
    {
        var alsoIn = "{\"source\": \"Sample/b/D.ROB\", \"entry\": \"C\", \"index\": 1, \"container\": \"rob\", " +
                     "\"storedSize\": 9, \"storedSha256\": \"" + StoredSha + "\"}";
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(alsoIn: alsoIn)));
        Assert.Contains("only a named XnGine BSA entry is LZSS-compressed", exception.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAnUnpinnedLzssCandidateOnARowThatPinsStoredBytes()
    {
        // The first generator draft emitted exactly this shape (an xngine-bsa alsoIn candidate with no stored
        // pins on a compressed row) on 5 rows; the resolver refuses it with a non-absent reason deep inside
        // Bucket B, so the parser now fails it in the default suite instead.
        var alsoIn = "{\"source\": \"Sample/b/3D.BSA\", \"entry\": \"C.3D\", \"index\": 4, " +
                     "\"container\": \"xngine-bsa\"}";
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(alsoIn: alsoIn)));
        Assert.Contains("carries no stored pins itself", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesASegmentTypeOnANonRobRow()
    {
        var exception = Assert.Throws<InvalidDataException>(() =>
            Cut1cCoverManifest.Parse(Manifest(segmentType1: ", \"segmentType\": 0")));
        Assert.Contains("segmentType is pinned exactly on a ROB row", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesASegmentTypeOnANonRobCandidate()
    {
        var alsoIn = "{\"source\": \"Sample/b/3D.BSA\", \"entry\": \"C.3D\", \"index\": 4, " +
                     "\"container\": \"xngine-bsa\", \"storedSize\": 9, \"storedSha256\": \"" + StoredSha +
                     "\", \"segmentType\": 0}";
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(alsoIn: alsoIn)));
        Assert.Contains("pins a segmentType exactly when it is a ROB segment", exception.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_ReadsARobRowsSegmentTypeIntoThePrimaryCandidate()
    {
        var files = Cut1cCoverManifest.Parse(RobManifest(", \"segmentType\": 512"));
        var row = Assert.Single(files);
        Assert.Equal(512, row.SegmentType);
        Assert.Equal(512, Assert.Single(row.Candidates).SegmentType);
    }

    [Fact]
    public void Parse_RefusesARobRowWithoutASegmentType()
    {
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(RobManifest("")));
        Assert.Contains("segmentType is pinned exactly on a ROB row", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesARepeatedCandidateIdentity()
    {
        var alsoIn = "{\"source\": \"Sample/a/3D.BS6\", \"entry\": \"C.3D\", \"index\": 3, " +
                     "\"container\": \"xngine-bsa\", \"storedSize\": 9, \"storedSha256\": \"" + StoredSha +
                     "\"}";
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(Manifest(alsoIn: alsoIn)));
        Assert.Contains("appears twice in the manifest", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesARepeatedRowName()
    {
        var json = Manifest().Replace("NAME2", "NAME1", StringComparison.Ordinal);
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(json));
        Assert.Contains("appears twice", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesASharedDigestWithoutASharedControl()
    {
        var json = Manifest().Replace(ArchiveSha, LooseSha, StringComparison.Ordinal);
        var exception = Assert.Throws<InvalidDataException>(() => Cut1cCoverManifest.Parse(json));
        Assert.Contains("share no control name", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_AcceptsASharedDigestInsideAControlGroup()
    {
        var json = Manifest(controls2: "{\"name\": \"the control\"}")
            .Replace(ArchiveSha, LooseSha, StringComparison.Ordinal);
        var files = Cut1cCoverManifest.Parse(json);
        Assert.Equal(files[0].Sha256, files[1].Sha256);
    }

    // ---------------------------------------------------------------- the checked-in manifest's measured facts

    [Fact]
    public void Manifest_HoldsThePlansCover()
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var files = Cut1cCoverManifest.Files;
        Assert.Equal(31, files.Count);
        Assert.Equal(8, files.Count(f => f.Role == Cut1cCoverFile.DesignRole));
        Assert.Equal(3, files.Count(f => f.Role == Cut1cCoverFile.ProposedRole));
        Assert.Equal(3, files.Count(f => f.Role == Cut1cCoverFile.AlternateRole));
        Assert.Equal(3, files.Count(f => f.Role == Cut1cCoverFile.DeclinedControlRole));
        Assert.Equal(14, files.Count(f => f.Role == Cut1cCoverFile.EdgeControlRole));
    }

    [Theory]
    [InlineData("arch3d-extracted-loose-ambiguity")]
    [InlineData("doga001-unit-control")]
    [InlineData("barstep1-bs6-cover")]
    [InlineData("3dc-offered-to-3d-reader")]
    [InlineData("fxart-v5-unsupported")]
    [InlineData("3dbsa-mz-stray")]
    [InlineData("empty-rob-segment")]
    [InlineData("menu-rob-static-h16")]
    [InlineData("espear-omitted-planes")]
    [InlineData("hbbld01-emptied-key-nonzero-normal")]
    [InlineData("folded-fan")]
    [InlineData("barstep1-3dbsa-namesake")]
    [InlineData("arch3d-unfold-changes-values")]
    [InlineData("bsa-repeated-point-plane")]
    [InlineData("rob-repeated-point-planes")]
    [InlineData("rob-legacy-unfold-accident")]
    public void Manifest_PinsEveryNamedControlOnce(string control)
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var file = Cut1cCoverManifest.RequireControl(control);
        Assert.Contains(control, file.Controls);
    }

    [Fact]
    public void Manifest_PinsTheBarstep1NamesakePairApartByDigestAlone()
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var cover = Cut1cCoverManifest.RequireControl("barstep1-bs6-cover");
        var namesake = Cut1cCoverManifest.RequireControl("barstep1-3dbsa-namesake");
        Assert.Equal(cover.Entry, namesake.Entry);
        Assert.Equal(437, cover.Index);
        Assert.Equal(438, namesake.Index);
        Assert.Equal(Barstep1Bs6Sha, cover.Sha256);
        Assert.Equal(Barstep1Bs6StoredSha, cover.StoredSha256);
        Assert.Equal(Barstep1NamesakeSha, namesake.Sha256);
        Assert.Equal(Barstep1NamesakeStoredSha, namesake.StoredSha256);

        // The pair has ONE payload size (1,540 bytes), so a size check cannot separate the copies; the digest must.
        Assert.Equal(cover.Size, namesake.Size);
        Assert.NotEqual(cover.Sha256, namesake.Sha256);
        Assert.NotEqual(cover.StoredSha256, namesake.StoredSha256);
    }

    [Fact]
    public void Manifest_PinsTheId5090GroupByIndex()
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var group = Cut1cCoverManifest.RequireGroup("id-5090-duplicate-group");
        Assert.Equal(6, group.Count);
        Assert.All(group, f => Assert.Equal("5090", f.Entry));
        Assert.Equal(new[] { 5007, 8903, 9787, 9824, 9826, 10238 },
            group.Select(f => f.Index!.Value).Order().ToArray());

        // 6 records, 5 distinct payloads: exactly the indices 5007 and 8903 are byte-identical.
        Assert.Equal(5, group.Select(f => f.Sha256).Distinct(StringComparer.Ordinal).Count());
        var twins = group.GroupBy(f => f.Sha256, StringComparer.Ordinal).Single(g => g.Count() > 1);
        Assert.Equal(new[] { 5007, 8903 }, twins.Select(f => f.Index!.Value).Order().ToArray());
    }

    [Fact]
    public void Manifest_PinsTheFoldedFanRowAsTheMZPick()
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var file = Cut1cCoverManifest.RequireControl("folded-fan");
        Assert.Equal("CAT02.3D", file.Entry);
        Assert.Equal(1111, file.Index);
        Assert.Equal(Cut1cCoverFile.XnGineBsaContainer, file.Container);
        Assert.Equal(1806, file.Size);
        Assert.Equal(Cat02Sha, file.Sha256);
        Assert.Equal(Cat02StoredSha, file.StoredSha256);
    }

    /// <summary>
    ///     The slice-5 review rows, each pinned here by container, index and digest so a regeneration that moves one fails
    ///     without any game install present: ARCH3D 409 (index 4762, 57,176 bytes), 3D.BSA PUZSPRT1.3D (#98, 15,650
    ///     decoded bytes, LZSS 5,274) and NECRISLE.ROB NCGATE01 (segment 108, type 0, 7,506 bytes), which carries two
    ///     controls.
    /// </summary>
    [Fact]
    public void Manifest_PinsTheSlice5ReviewRows()
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var unfold = Cut1cCoverManifest.RequireControl("arch3d-unfold-changes-values");
        Assert.Equal(Cut1cCoverFile.Arch3dContainer, unfold.Container);
        Assert.Equal("409", unfold.Entry);
        Assert.Equal(4762, unfold.Index);
        Assert.Equal(57176, unfold.Size);
        Assert.Equal(Arch3d409Sha, unfold.Sha256);

        var bsa = Cut1cCoverManifest.RequireControl("bsa-repeated-point-plane");
        Assert.Equal(Cut1cCoverFile.XnGineBsaContainer, bsa.Container);
        Assert.Equal("PUZSPRT1.3D", bsa.Entry);
        Assert.Equal(98, bsa.Index);
        Assert.Equal(15650, bsa.Size);
        Assert.Equal(Puzsprt1Sha, bsa.Sha256);
        Assert.Equal(5274L, bsa.StoredSize);
        Assert.Equal(Puzsprt1StoredSha, bsa.StoredSha256);

        var rob = Cut1cCoverManifest.RequireControl("rob-repeated-point-planes");
        Assert.Same(rob, Cut1cCoverManifest.RequireControl("rob-legacy-unfold-accident"));
        Assert.Equal(Cut1cCoverFile.RobContainer, rob.Container);
        Assert.Equal("NCGATE01", rob.Entry);
        Assert.Equal(108, rob.Index);
        Assert.Equal(0, rob.SegmentType);
        Assert.Equal(7506, rob.Size);
        Assert.Equal(Ncgate01Sha, rob.Sha256);
    }

    /// <summary>
    ///     Every static <c>.3D</c> row of the manifest has its slice-5 pins (<see cref="Cut1cXnGineCover.Pins" />) and no
    ///     pin names a row the manifest lacks, so a regenerated manifest cannot add a row the Bucket-B tests leave unpinned.
    /// </summary>
    [Fact]
    public void Manifest_EveryStaticRowHasItsSlice5Pins()
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var rows = Cut1cCoverManifest.Files.Where(Cut1cXnGineCover.IsStaticMesh).Select(f => f.Name)
            .Order(StringComparer.Ordinal).ToArray();

        Assert.Equal(22, rows.Length);
        Assert.Equal(rows, Cut1cXnGineCover.Pins.Keys.Order(StringComparer.Ordinal).ToArray());
    }

    [Fact]
    public void Manifest_PinsTheEmptySegmentAtTheDigestOfZeroBytes()
    {
        Assert.SkipWhen(Cut1cCoverManifest.Path is null, "The cut-1c cover manifest is not in this checkout.");
        var file = Cut1cCoverManifest.RequireControl("empty-rob-segment");
        Assert.Equal(0, file.Size);
        Assert.Equal(EmptySha, file.Sha256);
        Assert.Equal(Cut1cFixtureResolver.Sha256([]), file.Sha256);
    }

    private static string RobManifest(string segmentType)
    {
        return """
            {
             "tool": "cut1c_cover_manifest.py",
             "manifestSchema": 1,
             "options": {"scope": "cut1c", "payloads": true},
             "files": [
              {"role": "design", "name": "ROBROW", "game": "Redguard", "population": "redguard_rob_3dart",
               "container": "rob", "source": "Sample/a/D.ROB", "entry": "SEG0", "index": 0, "tag": "v2.7",
               "size": 10, "sha256": "LOOSESHA"SEGMENT, "alsoIn": [], "controls": [], "note": "n"}
             ]
            }
            """
            .Replace("LOOSESHA", LooseSha, StringComparison.Ordinal)
            .Replace("SEGMENT", segmentType, StringComparison.Ordinal);
    }

    private static string Manifest(string scope = Cut1cCoverManifest.Scope, string role = "design",
        string looseIndex = "null", string archiveIndex = "3", long looseSize = 10, string? declined = null,
        string alsoIn = "", string controls2 = "", string segmentType1 = "")
    {
        return ManifestJson
            .Replace("SCOPE", scope, StringComparison.Ordinal)
            .Replace("ROLE", role, StringComparison.Ordinal)
            .Replace("LOOSEINDEX", looseIndex, StringComparison.Ordinal)
            .Replace("ARCHIVEINDEX", archiveIndex, StringComparison.Ordinal)
            .Replace("LOOSESIZE", looseSize.ToString(System.Globalization.CultureInfo.InvariantCulture),
                StringComparison.Ordinal)
            .Replace("LOOSESHA", LooseSha, StringComparison.Ordinal)
            .Replace("ARCHIVESHA", ArchiveSha, StringComparison.Ordinal)
            .Replace("STOREDSIZE", "9", StringComparison.Ordinal)
            .Replace("STOREDSHA", "\"" + StoredSha + "\"", StringComparison.Ordinal)
            .Replace("CONTROLS1", "{\"name\": \"the control\"}", StringComparison.Ordinal)
            .Replace("CONTROLS2", controls2, StringComparison.Ordinal)
            .Replace("DECLINED1",
                declined is null ? "" : ", \"declined\": \"" + declined + "\"", StringComparison.Ordinal)
            .Replace("SEGTYPE1", segmentType1, StringComparison.Ordinal)
            .Replace("ALSOIN", alsoIn, StringComparison.Ordinal);
    }
}
