namespace BethesdaAudioTranscriber.Models;

/// <summary>
///     Root model for a .fnvreview.json sidecar file: suspected-typo flags for a build
///     directory, generated by tools/scripts/transcript_typo_check.py and resolved
///     interactively in the app.
/// </summary>
public class ReviewFile
{
    /// <summary>Tool that generated this file.</summary>
    public string GeneratedBy { get; set; } = "";

    /// <summary>When this file was generated.</summary>
    public DateTimeOffset GeneratedAt { get; set; }

    /// <summary>Suggestions keyed by "voicetype|FORMID_ResponseIndex".</summary>
    public Dictionary<string, ReviewSuggestion> Entries { get; set; } = new(StringComparer.OrdinalIgnoreCase);
}
