using System.Globalization;
using System.Text;
using EsmSchemaGen.Ir;

namespace EsmSchemaGen.Emit;

/// <summary>
///     Emits a per-game schema as a C# source file that instantiates the runtime schema types in
///     <c>BethesdaMultitool.Core.Formats.Esm.RecordModel.Schema</c>. Output is committed under the main
///     library's <c>RecordModel/Generated</c> folder. Regeneration is an explicit, reviewed operation;
///     the local xEdit source tree is not available to clean CI. Deterministic LF output keeps reviewed
///     diffs stable across platforms.
/// </summary>
public static class SchemaEmitter
{
    private const char Nl = '\n';

    public static string EmitGame(string className, IReadOnlyList<RecordDef> records)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/> Generated by tools/EsmSchemaGen from the xEdit (TES5Edit) record").Append(Nl);
        sb.Append("// definitions. DO NOT EDIT — re-run the generator instead.").Append(Nl);
        sb.Append("using System.Collections.Generic;").Append(Nl);
        sb.Append("using BethesdaMultitool.Core.Formats.Esm.RecordModel.Schema;").Append(Nl);
        sb.Append(Nl);
        sb.Append("namespace BethesdaMultitool.Core.Formats.Esm.RecordModel.Generated;").Append(Nl);
        sb.Append(Nl);
        sb.Append("public static class ").Append(className).Append(Nl);
        sb.Append('{').Append(Nl);
        sb.Append("    public static IReadOnlyList<RecordDef> Records { get; } =").Append(Nl);
        sb.Append("    [").Append(Nl);
        foreach (var record in records)
        {
            sb.Append(EmitRecord(record, 2)).Append(',').Append(Nl);
        }

        sb.Append("    ];").Append(Nl);
        sb.Append('}').Append(Nl);
        return sb.ToString();
    }

    private static string EmitRecord(RecordDef record, int indent)
    {
        var pad = Indent(indent);
        return pad + "new RecordDef(" + Quote(record.Signature) + "," + Nl +
               EmitList(record.Members, indent + 1) + Nl +
               pad + ")" + InitBlock(record);
    }

    private static string EmitNode(MemberDef member, int indent)
    {
        var pad = Indent(indent);
        switch (member)
        {
            case FieldDef field:
                return pad + "new FieldDef(PrimType." + field.Type + ")" + InitBlock(field);
            case FormIdDef formId:
                return pad + "new FormIdDef" + InitBlock(formId);
            case UnusedDef unused:
                return pad + "new UnusedDef(" + unused.Size + ")" + InitBlock(unused);
            case EmptyDef:
                return pad + "new EmptyDef" + InitBlock(member);
            case UnknownMemberDef unknown:
                return pad + "new RawMemberDef(" + Quote(unknown.CallName) + ")" + InitBlock(unknown);
            case StructDef structDef:
                return pad + "new StructDef(" + Nl +
                       EmitList(structDef.Members, indent + 1) + Nl +
                       pad + ")" + InitBlock(structDef);
            case ArrayDef array:
                return pad + "new ArrayDef(" + Nl +
                       EmitNode(array.Element, indent + 1) + Nl +
                       pad + ")" + InitBlock(array);
            case UnionDef union:
                return pad + "new UnionDef(" + Quote(union.DeciderName) + "," + Nl +
                       EmitList(union.Variants, indent + 1) + Nl +
                       pad + ")" + InitBlock(union);
            default:
                return pad + "new RawMemberDef(" + Quote(member.GetType().Name) + ")";
        }
    }

    private static string EmitList(IReadOnlyList<MemberDef> members, int indent)
    {
        var pad = Indent(indent);
        if (members.Count == 0)
        {
            return pad + "[]";
        }

        var items = string.Join("," + Nl, members.Select(m => EmitNode(m, indent + 1)));
        return pad + "[" + Nl + items + Nl + pad + "]";
    }

    private static string InitBlock(SchemaNode node)
    {
        var props = new List<string>();

        if (node is MemberDef { Signature: { } sig })
        {
            props.Add($"Signature = {Quote(sig)}");
        }

        if (node is MemberDef { MinFormVersion: { } minFormVersion })
        {
            props.Add($"MinFormVersion = {minFormVersion}");
        }

        if (node is MemberDef { MaxFormVersionExclusive: { } maxFormVersionExclusive })
        {
            props.Add($"MaxFormVersionExclusive = {maxFormVersionExclusive}");
        }

        if (node.Name is { } name)
        {
            props.Add($"Name = {Quote(name)}");
        }

        if (node.Required)
        {
            props.Add("Required = true");
        }

        if (node.DefaultValue is { } def)
        {
            props.Add($"DefaultValue = {def.ToString(CultureInfo.InvariantCulture)}");
        }

        switch (node)
        {
            case FieldDef field:
                if (field.FixedSize is { } fixedSize)
                {
                    props.Add($"FixedSize = {fixedSize}");
                }

                if (field.EnumRefName is { } enumRef)
                {
                    props.Add($"EnumRefName = {Quote(enumRef)}");
                }

                if (field.InlineEnum is { } inlineEnum)
                {
                    props.Add($"InlineEnum = {EmitEnum(inlineEnum)}");
                }

                if (field.InlineFlags is { } inlineFlags)
                {
                    props.Add($"InlineFlags = {EmitFlags(inlineFlags)}");
                }

                break;
            case FormIdDef { Targets.Count: > 0 } formId:
                props.Add($"Targets = [{string.Join(", ", formId.Targets.Select(Quote))}]");
                break;
            case ArrayDef array:
                props.Add($"Count = {array.Count}");
                if (array.CountRef is { } countRef)
                {
                    props.Add($"CountRef = {Quote(countRef)}");
                }

                break;
        }

        return props.Count == 0 ? string.Empty : " { " + string.Join(", ", props) + " }";
    }

    private static string EmitEnum(EnumDef e)
    {
        var members = string.Join(", ", e.Members.Select(m => $"new EnumMember({m.Value}, {Quote(m.Label)})"));
        return $"new EnumDef({(e.Name is null ? "null" : Quote(e.Name))}, [{members}])";
    }

    private static string EmitFlags(FlagsDef f)
    {
        var bits = string.Join(", ", f.Bits.Select(b => $"new FlagMember({b.Bit}, {Quote(b.Label)})"));
        return $"new FlagsDef({(f.Name is null ? "null" : Quote(f.Name))}, [{bits}])";
    }

    private static string Indent(int level) => new(' ', level * 4);

    private static string Quote(string value)
    {
        var escaped = value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
        return "\"" + escaped + "\"";
    }
}
