using System.Linq;
using System.Numerics;
using BethesdaMultitool.Core.Formats.Xngine.Mesh;
using Xunit;

namespace BethesdaMultitool.Tests.Core.Formats.Xngine.Mesh;

/// <summary>
///     Plane decomposition: delta UVs on triangles, fitted UVs and corner filtering on polygons,
///     fan triangulation and per-texture grouping.
/// </summary>
public class XnGineMeshDecomposerTests
{
    /// <summary>The corner indices of the collinear-run polygon below.</summary>
    private static readonly int[] ExpectedCorners = [0, 2, 3];

    [Fact]
    public void Decompose_Triangle_AccumulatesDeltaUvs_AndScalesToWorldUnits()
    {
        var bytes = XnGineMeshFixture.Build("v2.7",
            [(0, 0, 0), (256, 0, 0), (256, -256, 0)],
            [new XnGineMeshFixture.Plane(XnGineMeshFixture.Texture(24, 3), [(0, 16, 32), (1, 1008, 0), (2, 0, 992)], (0, 0, -256))]);

        var mesh = XnGineMeshDecomposer.Decompose(XnGineMesh.Parse(bytes, 5000));

        var subMesh = Assert.Single(mesh.SubMeshes);
        Assert.Equal(24, subMesh.TextureArchive);
        Assert.Equal(3, subMesh.TextureRecord);
        Assert.Equal(1, subMesh.TriangleCount);
        Assert.Equal([0, 1, 2], subMesh.Indices);

        Assert.Equal(new Vector3(1, -1, 0), subMesh.Vertices[2].Position);
        Assert.Equal(new Vector3(0, 0, -1), subMesh.Vertices[0].Normal);
        Assert.Equal(new Vector2(1, 2), subMesh.Vertices[0].TexelUv);
        Assert.Equal(new Vector2(64, 2), subMesh.Vertices[1].TexelUv);
        Assert.Equal(new Vector2(64, 64), subMesh.Vertices[2].TexelUv);
    }

    [Fact]
    public void Decompose_Quad_FitsTheFourthUv_AndFansTwoTriangles()
    {
        var mesh = XnGineMeshDecomposer.Decompose(XnGineMesh.Parse(XnGineMeshFixture.Quad(), 5000));

        var subMesh = Assert.Single(mesh.SubMeshes);
        Assert.Equal(4, subMesh.Vertices.Count);
        Assert.Equal(2, subMesh.TriangleCount);
        Assert.Equal([0, 1, 2, 0, 2, 3], subMesh.Indices);

        // The first three UVs are the accumulated authored ones; the fourth is generated by the fit
        // (U = 4x, V = 4z in native units → texel (0, 64) for the corner at (0, 0, 256)). The
        // reference's corner walk starts at point 1, so the vertices come out rotated by one.
        Assert.Equal(new Vector2(64, 0), subMesh.Vertices[0].TexelUv);
        Assert.Equal(new Vector2(64, 64), subMesh.Vertices[1].TexelUv);
        Assert.Equal(new Vector2(0, 64), subMesh.Vertices[2].TexelUv);
        Assert.Equal(new Vector2(0, 0), subMesh.Vertices[3].TexelUv);
        Assert.Equal(new Vector3(0, 0, 1), subMesh.Vertices[2].Position);
        Assert.Equal(new Vector3(0, -1, 0), subMesh.Vertices[2].Normal);
    }

    [Fact]
    public void Decompose_DropsCollinearPoints_KeepsCorners()
    {
        // A quad with an extra point in the middle of its first edge.
        var bytes = XnGineMeshFixture.Build("v2.7",
            [(0, 0, 0), (128, 0, 0), (256, 0, 0), (256, 0, 256), (0, 0, 256)],
            [new XnGineMeshFixture.Plane(XnGineMeshFixture.Texture(1, 0), [(0, 0, 0), (1, 512, 0), (2, 512, 0), (3, 0, 1024), (4, 0, 0)], (0, -256, 0))]);

        var mesh = XnGineMeshDecomposer.Decompose(XnGineMesh.Parse(bytes, 5000));

        var subMesh = Assert.Single(mesh.SubMeshes);
        Assert.Equal(4, subMesh.Vertices.Count);
        Assert.DoesNotContain(subMesh.Vertices, v => v.Position == new Vector3(0.5f, 0, 0));
        Assert.Equal(2, subMesh.TriangleCount);
    }

    [Fact]
    public void Decompose_GroupsPlanesByTexture_InFirstUseOrder()
    {
        var bytes = XnGineMeshFixture.Build("v2.7",
            [(0, 0, 0), (256, 0, 0), (256, 0, 256), (0, 0, 256)],
            [
                new XnGineMeshFixture.Plane(XnGineMeshFixture.Texture(24, 0), [(0, 0, 0), (1, 0, 0), (2, 0, 0)], (0, -256, 0)),
                new XnGineMeshFixture.Plane(XnGineMeshFixture.Texture(321, 4), [(0, 0, 0), (2, 0, 0), (3, 0, 0)], (0, -256, 0)),
                new XnGineMeshFixture.Plane(XnGineMeshFixture.Texture(24, 0), [(1, 0, 0), (2, 0, 0), (3, 0, 0)], (0, -256, 0))
            ]);

        var mesh = XnGineMeshDecomposer.Decompose(XnGineMesh.Parse(bytes, 5000));

        Assert.Equal(2, mesh.SubMeshes.Count);
        Assert.Equal((24, 0, 2), (mesh.SubMeshes[0].TextureArchive, mesh.SubMeshes[0].TextureRecord, mesh.SubMeshes[0].TriangleCount));
        Assert.Equal((321, 4, 1), (mesh.SubMeshes[1].TextureArchive, mesh.SubMeshes[1].TextureRecord, mesh.SubMeshes[1].TriangleCount));
        Assert.Equal(3, mesh.TriangleCount);
        Assert.Equal(9, mesh.VertexCount);
    }

    [Fact]
    public void ComputeFaceUv_ReturnsNull_ForCollinearLeadingPoints()
    {
        var points = new[]
        {
            new XnGineMeshDecomposer.PurePoint(new Vector3(0, 0, 0), Vector3.UnitY, 0, 0),
            new XnGineMeshDecomposer.PurePoint(new Vector3(128, 0, 0), Vector3.UnitY, 0, 0),
            new XnGineMeshDecomposer.PurePoint(new Vector3(256, 0, 0), Vector3.UnitY, 0, 0),
            new XnGineMeshDecomposer.PurePoint(new Vector3(256, 0, 256), Vector3.UnitY, 0, 0)
        };

        Assert.Null(XnGineMeshDecomposer.ComputeFaceUv(points));
        // Point 1 sits on the straight run 0-1-2 and is the only non-corner.
        Assert.Equal(ExpectedCorners, XnGineMeshDecomposer.CornerIndices(points).OrderBy(i => i));
    }
}
