// ORIGINAL CLEAN-ROOM IMPLEMENTATION.
//
// Written from our own reverse engineering of RAD Game Tools' shipped decoder binkw32.dll
// (Fallout Tactics, md5 ecbd8213e89f8afde368f8eb05ff5a9c), via our Ghidra decompilation at
// tools/GhidraProject/ClassicRE/binkw32.dll.decompiled.txt and our own capstone disassembly of the
// same file, as written up in the specification document
//   scratchpad .../cleanroom/bink/SPEC.md  ("Bink Video (BIKi) - Format Specification"), section 8
//   (_YUV_init@4 at 0x3000BED0, generator loop at 0x3000BF0C).
//
// NO FFmpeg- or libav-derived code, and no other third-party Bink implementation, was consulted,
// read, copied or paraphrased. ffmpeg was used only as a sealed black box, comparing output pixels.

namespace BethesdaMultitool.Core.Formats.Bink;

/// <summary>
///     Bink's YUV to RGB conversion, built the way <c>binkw32.dll</c> builds it at load time: five
///     256-entry tables generated by one 256-iteration loop, then three table lookups and a clamp
///     per pixel.
///     <para>
///         The result is BT.601 LIMITED range (luma 16..235, chroma centred on 128) expanded to
///         full-range 0..255 RGB. Two details are the DLL's, not an approximation of it: the luma
///         scale is <c>0x950A / 32768</c> = 255/219 with truncation TOWARD ZERO, and the top of the
///         luma ramp saturates at 254, not 255.
///     </para>
///     <para>
///         Cross-checked against ffmpeg's <c>rgb24</c> output on a retail frame: 33.99% of channels
///         exactly equal, 99.996% within ±1, maximum difference 3. A wrong coefficient would show a
///         hue-shaped error growing with distance from 128; none is present.
///     </para>
/// </summary>
internal static class BinkColorConverter
{
    private static readonly int[] LumaTable = new int[256];
    private static readonly int[] RedFromV = new int[256];
    private static readonly int[] GreenFromV = new int[256];
    private static readonly int[] GreenFromU = new int[256];
    private static readonly int[] BlueFromU = new int[256];

    static BinkColorConverter()
    {
        // The four accumulators and their per-iteration deltas are literals in _YUV_init@4.
        var greenV = 0x340780;
        var redV = -0x662580;
        var blueU = -0x811A80;
        var greenU = 0x191280;

        for (var i = 0; i < 256; i++)
        {
            // The luma ramp's three arms are selected by the accumulator's own value, which is how
            // the DLL spells "i <= 16", "17..234" and "i >= 235" without a second counter.
            int limited;
            if (greenV >= 0x2D8690)
            {
                limited = 0;
            }
            else if (greenV > -0x2B7E45)
            {
                limited = i - 16;
            }
            else
            {
                limited = 219;
            }

            LumaTable[i] = TruncateBy32768(limited * 0x950A);
            GreenFromV[i] = TruncateBy32768(greenV);
            GreenFromU[i] = TruncateBy32768(greenU);
            RedFromV[i] = TruncateBy32768(redV);
            BlueFromU[i] = TruncateBy32768(blueU);

            greenV -= 0x680F;
            redV += 0xCC4B;
            blueU += 0x10235;
            greenU -= 0x3225;
        }
    }

    /// <summary>
    ///     Converts a decoded frame's three planes to opaque RGBA, replicating chroma 2x2 (the
    ///     DLL's <c>_YUV_blit_*</c> family replicates too; ffmpeg interpolates, which is the whole
    ///     of the ±1 residue in the class summary).
    ///     <para>
    ///         There is deliberately NO alpha-plane input. A stream with the alpha flag (0x100000)
    ///         is refused by <see cref="BinkVideoDecoder" /> before any plane is decoded, because
    ///         no file in the 59-movie corpus carries one and the DLL's pass-through of that plane
    ///         (<c>_YUV_blit_32abpp</c>) has therefore never been measured here. Wiring an
    ///         unmeasured path so that it silently produced pixels is what the earlier, dead
    ///         <c>alpha</c> parameter amounted to; it was removed rather than left looking wired.
    ///     </para>
    /// </summary>
    internal static byte[] ToRgba(BinkPlane luma, BinkPlane chromaV, BinkPlane chromaU, int width, int height)
    {
        ArgumentNullException.ThrowIfNull(luma);
        ArgumentNullException.ThrowIfNull(chromaV);
        ArgumentNullException.ThrowIfNull(chromaU);

        var rgba = new byte[width * height * 4];
        for (var y = 0; y < height; y++)
        {
            var lumaRow = luma.OffsetOf(0, y);
            var chromaRow = chromaV.OffsetOf(0, y >> 1);
            var chromaURow = chromaU.OffsetOf(0, y >> 1);
            var destination = y * width * 4;

            for (var x = 0; x < width; x++)
            {
                var brightness = LumaTable[luma.Pixels[lumaRow + x]];
                var v = chromaV.Pixels[chromaRow + (x >> 1)];
                var u = chromaU.Pixels[chromaURow + (x >> 1)];

                var at = destination + x * 4;
                rgba[at] = Clamp(brightness + RedFromV[v]);
                rgba[at + 1] = Clamp(brightness + GreenFromV[v] + GreenFromU[u]);
                rgba[at + 2] = Clamp(brightness + BlueFromU[u]);
                rgba[at + 3] = 255;
            }
        }

        return rgba;
    }

    /// <summary>
    ///     Truncate-toward-zero division by 32768, coded in the DLL as
    ///     <c>(x + (x&gt;&gt;31 &amp; 0x7fff)) &gt;&gt; 15</c>.
    /// </summary>
    private static int TruncateBy32768(int value)
    {
        return (value + ((value >> 31) & 0x7FFF)) >> 15;
    }

    private static byte Clamp(int value)
    {
        return (byte)Math.Clamp(value, 0, 255);
    }
}
